version: '3'
services:

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress-data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=example
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb
    networks:
      - Inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    networks:
      - Inception
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    networks:
      - Inception
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=example
    volumes:
      - mariadb-data:/var/lib/mysql

networks:
  Inception:
    driver: bridge

volumes:
  wordpress-data:
  mariadb-data:
