version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 443:443
    # volumes:
    #   - nginx-conf:/etc/nginx/conf.d
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:php7.4-fpm
    volumes:
      - wordpress-data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=example
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=example
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  wordpress-data:
  mariadb-data: