version: '3'
services:
	nginx:
		image: nginx
		volumes:
			- /requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
		ports:
			- 443
		depends_on:
			- wordpress

	wordpress:
		image: wordpress
		volumes:
			- wordpress_data:/var/www/html
		#environment:
			#- WORDPRESS_DB_HOST=mariadb
			#- WORDPRESS_DB_USER=root
			# - WORDPRESS_DB_PASSWORD=secret
			# - WORDPRESS_DB_NAME=wordpress
		depends_on:
			- mariadb

	mariadb:
		image: mariadb
		volumes:
			- mariadb_data:/var/lib/mysql
		environment:
			- MYSQL_ROOT_PASSWORD=secret
			- MYSQL_DATABASE=wordpress

volumes:
	wordpress_data:
	mariadb_data:
