version: '3'
services:

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 9000:9000
    volumes:
      - wordpress-data:/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - Inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    networks:
      - Inception
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
  mariadb:
    build: 
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    networks:
      - Inception
    volumes:
      - mariadb-data:/var/lib/mysql

networks:
  Inception:
    driver: bridge

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/yobenali/data/wordpress
  mariadb-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/yobenali/data/mariadb
